# Generated by Django 3.2 on 2023-01-20 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Inici', models.DateField(blank=True, error_messages={'invalid': 'Ingrese una fecha válida.'})),
            ],
        ),
        migrations.CreateModel(
            name='carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('Nomcant', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomh', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nommt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='modalidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomm', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('Nomp', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='provincia',
            fields=[
                ('Nomprov', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Nompai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Crud.pais')),
            ],
        ),
        migrations.CreateModel(
            name='tpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido_P', models.CharField(max_length=50)),
                ('Apellido_M', models.CharField(max_length=50)),
                ('Fecha_Nac', models.DateField()),
                ('Telf_Celular', models.CharField(max_length=15)),
                ('Usu_Django', models.CharField(max_length=50)),
                ('N_Identificacion', models.CharField(max_length=13)),
                ('Ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud.ciudad')),
                ('Pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud.pais')),
                ('Provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud.provincia')),
                ('T_Identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud.tpi')),
            ],
        ),
        migrations.CreateModel(
            name='profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Inic', models.DateField(blank=True, error_messages={'invalid': 'Ingrese una fecha válida.'})),
                ('Estado', models.BooleanField(default=False)),
                ('usup', models.ForeignKey(blank=True, error_messages={'required': 'Selecione al estudiante'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crud.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hora', models.TimeField()),
                ('Dia', models.CharField(choices=[('', 'Seleccione el día'), ('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], error_messages={'required': 'Selecciona un dia.'}, max_length=10)),
                ('Fecha_Inicio', models.DateField()),
                ('Fecha_Fin', models.DateField()),
                ('Alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud.alumnos')),
                ('Materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud.materias')),
                ('Modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud.modalidades')),
                ('Profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud.profesores')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='Nomprov',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Crud.provincia'),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='Nom_carr',
            field=models.ForeignKey(blank=True, error_messages={'required': 'Seleciona la carrera'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crud.carrera'),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='usua',
            field=models.ForeignKey(blank=True, error_messages={'required': 'Selecione al estudiante'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crud.usuarios'),
        ),
    ]
